# This stack creates the Event and Lambda that manages the creation and removal of 
# an EC2 resource including the Lambda that manages the removal itself
# boto3 examples https://www.programcreek.com/python/example/97943/boto3.client
# EventBridge: https://aws.amazon.com/eventbridge/faqs/

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CreateEC2StackName:
    Description: Name of the EC2 stack to be created
    Type: String
    Default: create-ec2-stack
  CreateEC2SCloudFormation:
    Description: Name of the CloudFormation template for EC2 creation
    Type: String
    Default: LambdaAMILookupSample-win.yml
  RemoveLambdaStackName:
    Description: Name of the remove Lambda stack to be created
    Type: String
    Default: remove-stack
  RemoveLambdaS3CloudFormation:
    Description: Name of the S3 bucket for the remove Lambda
    Type: String
    Default: destroy-stack.yml
  RemoveLambdaCronSchedule:
    Description: Schedule for the remove-lambda
    Type: String
    Default: cron(0/20 * * * ? *)
  CfnStackS3BucketName:
    Description: Name of the S3 bucket for the CloudFormation templates
    Type: String
    Default: http://s3.amazonaws.com/318-auto-deploy

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName: !Sub /aws/lambda/${CreateLambda}

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DeleteLogGroup 
              - logs:PutRetentionPolicy
            Resource: arn:aws:logs:*:*:*
          
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
            Resource: "*"
          
          - Effect: Allow
            Action: 
              - iam:CreateRole
              - iam:DeleteRolePolicy
              - iam:DeleteRole
              - iam:PutRolePolicy
              - iam:GetRolePolicy
              - iam:GetRole
              - iam:PassRole
            Resource: "*"
          
          - Effect: Allow
            Action: 
              - lambda:*
            Resource: "*"

          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource: arn:aws:s3:::*

          - Effect: Allow
            Action:
              - events:RemoveTargets
              - events:DeleteRule
              - events:PutRule 
              - events:DescribeRule
              - events:PutTargets 
            Resource: "*"
          
          - Effect: Allow
            Action:
              - ec2:TerminateInstances
              - ec2:DescribeInstances 
              - ec2:RunInstances 
            Resource: "*"

  CreateLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.6
      Environment:
        Variables:
          vCreateEC2StackName: !Ref CreateEC2StackName
          vCreateEC2SCloudFormation: !Join ['/', [!Ref CfnStackS3BucketName, !Ref CreateEC2SCloudFormation]]
          vRemoveLambdaStackName: !Ref RemoveLambdaStackName
          vRemoveLambdaS3CloudFormation: !Join ['/', [!Ref CfnStackS3BucketName, !Ref RemoveLambdaS3CloudFormation]]
          vRemoveLambdaCronSchedule: !Ref RemoveLambdaCronSchedule
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import os
          import logging
          import botocore

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          cf_client = boto3.client('cloudformation')

          def handler(event, context):
            try:
                resp = cf_client.describe_stacks(StackName = os.environ['vCreateEC2StackName'])
                print("Stack already existed:" + os.environ['vCreateEC2StackName'])
            except botocore.exceptions.ClientError as e:
                if 'does not exist' in e.response['Error']['Message']:
                  print("Creating automated EC2 stack:" + os.environ['vCreateEC2StackName'])
                  cf_client.create_stack(
                      StackName = os.environ['vCreateEC2StackName'],
                      TemplateURL = os.environ['vCreateEC2SCloudFormation'],
                      Capabilities=['CAPABILITY_IAM']
                  )

            try:
                resp = cf_client.describe_stacks(StackName = os.environ['vRemoveLambdaStackName'])
                print("Stack already existed:" + os.environ['vRemoveLambdaStackName'])      
            except botocore.exceptions.ClientError as e:
                if 'does not exist' in e.response['Error']['Message']:
                  print("Creating destoyer stack:" + os.environ['vRemoveLambdaStackName'])
                  cf_client.create_stack(
                      StackName = os.environ['vRemoveLambdaStackName'],
                      TemplateURL = os.environ['vRemoveLambdaS3CloudFormation'],
                      Capabilities=['CAPABILITY_IAM'],
                      Parameters=
                      [
                        {
                            'ParameterKey': 'TargetStackName',
                            'ParameterValue': os.environ['vCreateEC2StackName'],
                            'UsePreviousValue': False,
                            'ResolvedValue': 'string'
                        },
                        {
                            'ParameterKey': 'CronSchedule',
                            'ParameterValue': os.environ['vRemoveLambdaCronSchedule'],
                            'UsePreviousValue': False,
                            'ResolvedValue': 'string'
                        },
                      ]
                    )
                
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "CreateLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "CreateLambdaRule"
          - "Arn"      
          
  CreateLambdaRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: "Rule for the Lambda to schedule create and delete EC2"
      ScheduleExpression: "cron(0/15 * * * ? *)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "CreateLambda"
              - "Arn"
          Id: "CreateLambdaV1"
          Input: !Sub
          - "{\"StackName\": \"${Stack}\"}"
          - { Stack: !Ref "CreateEC2StackName" }       
