AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TargetStackName:
    Description: The name of the stack to be destroyed
    Type: String
  CronSchedule:
    Description: Schedule when this will be run
    Type: String

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DeleteLogGroup
              - logs:PutRetentionPolicy
            Resource: arn:aws:logs:*:*:*
          
          - Effect: Allow
            Action:
              - cloudformation:DeleteStack
            Resource: "*"
          
          - Effect: Allow
            Action: 
              - iam:DeleteRolePolicy
              - iam:DeleteRole
            Resource: "*"
          
          - Effect: Allow
            Action:
              - events:RemoveTargets
              - events:DeleteRule
            Resource: "*"

          - Effect: Allow
            Action:
              - ec2:TerminateInstances
              - ec2:DescribeInstances 
            Resource: "*"

          - Effect: Allow
            Action: 
              - lambda:RemovePermission
              - lambda:InvokeFunction
              - lambda:DeleteFunction
            Resource: "*"

  RemoveLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.6
      Environment:
        Variables:
          vTargetStackName: !Ref TargetStackName
          vOwnStackName: !Ref AWS::StackName
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          client = boto3.client('cloudformation')

          def handler(event, context):
            try:
              print("Deleting EC2 stack: " + os.environ['vTargetStackName'])
              client.delete_stack(
                  StackName=os.environ['vTargetStackName']
              )

              print("Deleting itself: " + os.environ['vOwnStackName'])
              client.delete_stack(
                  StackName=os.environ['vOwnStackName']
              )
              return "SUCCESS"
            except:
              return "ERROR"

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "RemoveLambda"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "RemoveRule"
          - "Arn"      
          
  RemoveRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: "Rule for the Lambda to schedule removing an EC2 stack"
      ScheduleExpression: !Ref CronSchedule 
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "RemoveLambda"
              - "Arn"
          Id: "RemoveLambda"
          Input: !Sub
          - "{\"StackName\": \"${Stack}\"}"
          - { Stack: !Ref "TargetStackName" }       
          
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1
      LogGroupName: !Sub /aws/lambda/${RemoveLambda}           
